/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BouquetRouteImport } from './routes/bouquet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorldIdRouteImport } from './routes/world.$id'

const BouquetRoute = BouquetRouteImport.update({
  id: '/bouquet',
  path: '/bouquet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldIdRoute = WorldIdRouteImport.update({
  id: '/world/$id',
  path: '/world/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bouquet': typeof BouquetRoute
  '/world/$id': typeof WorldIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bouquet': typeof BouquetRoute
  '/world/$id': typeof WorldIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bouquet': typeof BouquetRoute
  '/world/$id': typeof WorldIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bouquet' | '/world/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bouquet' | '/world/$id'
  id: '__root__' | '/' | '/bouquet' | '/world/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BouquetRoute: typeof BouquetRoute
  WorldIdRoute: typeof WorldIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bouquet': {
      id: '/bouquet'
      path: '/bouquet'
      fullPath: '/bouquet'
      preLoaderRoute: typeof BouquetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/$id': {
      id: '/world/$id'
      path: '/world/$id'
      fullPath: '/world/$id'
      preLoaderRoute: typeof WorldIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BouquetRoute: BouquetRoute,
  WorldIdRoute: WorldIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
